tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
brew "bash-completion"
brew "bundler-completion"
brew "python@3.9"
brew "cask"
brew "ffmpeg"
brew "git"
brew "htop"
brew "macvim", link: false
brew "mas"
brew "node"
brew "spaceship"
brew "speedtest-cli"
brew "tree"
brew "vim"
brew "youtube-dl"
brew "zsh"
cask "appzapper"
cask "bartender"
cask "cyberduck"
cask "flux"
cask "font-fira-code"
cask "font-inconsolata"
cask "maccy"
cask "mactex"
cask "nordvpn"
cask "pdf-expert"
cask "rectangle"
cask "visual-studio-code"
cask "macdown"
cask "scroll-reverser"
cask "notion"
mas "Amphetamine", id: 937984704
mas "Notability", id: 360593530
mas "Termius", id: 1176074088
mas "The Unarchiver", id: 425424353
mas "Wipr", id: 1320666476
